development:
  adapter: postgresql
  database: kazemb_development
  pool: 15
  timeout: 5000

test:
  adapter: postgresql
  database: kazemb_test
  pool: 15
  timeout: 5000

production:
  adapter: postgresql
  username: deploy
  password: 220888ok
  database: kazemb_production
  pool: 15
  timeout: 5000