development:
  adapter: postgresql
  database: kazemb_development
  pool: 15
  timeout: 5000

test:
  adapter: postgresql
  database: kazemb_test
  pool: 15
  timeout: 5000

production:
  adapter: postgresql
  username: ENV["DB_USERNAME"]
  password: ENV["DB_PASSWORD"]
  database: deploy
  pool: 15
  timeout: 5000