development:
  adapter: postgresql
  database: kazemb_development
  pool: 15
  timeout: 5000

test:
  adapter: postgresql
  database: kazemb_test
  pool: 15
  timeout: 5000

production:
  adapter: postgresql
  username: mansur
  password: 1234
  database: mansur
  pool: 15
  timeout: 5000